//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-09-27 11:10:34
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using NBCZ.Model;
using NBCZ.DAL.Interface;

namespace NBCZ.DAL.Impl
{	
	public partial class Pub_FunctionDAL:BaseDataDapperContrib<Pub_Function>,IPub_FunctionDAL
    { 
		
    }
}

      
