//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-03-25 09:03:23
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace NBCZ.Model
{	

    public partial class Pub_Function
    {

	       /// <summary>
     	/// 权限编号
     	/// </summary>
		public string FunctionCode { get; set; }

		    /// <summary>
     	/// 英文编号
     	/// </summary>
		public string FunctionEnglish { get; set; }

		    /// <summary>
     	/// 中文名称
     	/// </summary>
		public string FunctionChina { get; set; }

		    /// <summary>
     	/// 说明
     	/// </summary>
		public string FunctionDescrip { get; set; }

		    /// <summary>
     	/// 父节点
     	/// </summary>
		public string ParentCode { get; set; }

		    /// <summary>
     	/// 是否为菜单 1菜单 0权限
     	/// </summary>
		public bool MenuFlag { get; set; }

		    /// <summary>
     	/// 是否停用
     	/// </summary>
		public bool? StopFlag { get; set; }

		    /// <summary>
     	/// 链接URL
     	/// </summary>
		public string URLString { get; set; }

		    /// <summary>
     	/// 创建或修改时间
     	/// </summary>
		public DateTime? editdate { get; set; }

		    /// <summary>
     	/// 修改人 名字加工号 张三(000001)
     	/// </summary>
		public string editor { get; set; }

		    /// <summary>
     	/// 排序字段
     	/// </summary>
		public int? sortidx { get; set; }

		    /// <summary>
     	/// navTab 嵌套  _blank 新窗口 dialog 弹出窗
     	/// </summary>
		public string target { get; set; }

		    /// <summary>
     	/// 菜单图标class
     	/// </summary>
		public string MenuIcon { get; set; }

		   
    }
}

