//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-09-27 15:01:15
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using NBCZ.Model;

namespace NBCZ.DAL.Interface
{	
	public partial interface IV_PubFunction_ParentDAL:IBaseData<V_PubFunction_Parent>
    { 
		
    }
}

      
