//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-09-27 13:31:29
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using NBCZ.Model;
using NBCZ.BLL.Interface;

namespace NBCZ.BLL.Impl
{	
	public partial class V_PubUser_DeptBLL:BaseServiceDapperContrib<Model.V_PubUser_Dept>,IV_PubUser_DeptBLL
    {

    }
}

