//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-08-12 11:24:04
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using NBCZ.Model;
using NBCZ.DAL;

namespace NBCZ.BLL
{	
	public partial class V_PubFunction_ParentBLL:BaseServiceDapperContrib<Model.V_PubFunction_Parent>
    {
     

    }
}

