//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-08-09 10:02:49
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using NBCZ.Model;

namespace NBCZ.DAL
{	
	public partial class V_PubDept_ParentDAL:BaseDataDapperContrib<V_PubDept_Parent>
    { 
		
    }
}

      
